PAYMENT_ACCOUNT_OPTIONS = [
    "Caja Tda",
    "Tarjetas Visanet",
    "Tarjetas Mercadopago",
    "Tarjetas MCM",
    "Tarjetas Expressnet",
    "Pago Izipay",
    "Tarjetas Diners",
    "Tarjetas Estilos",
    "Efectivo Activa",
    "Deposito BCP",
    "Deposito Scotiabank",
    "Deposito Interbank",
    "Deposito BBVA",
    "Tarjetas Openpay",
]
