PAYMENT_ACCOUNT_OPTIONS = [
    "Caja Tda",
    "Cuentas por pagar - saldo",
    "Puntos y obsequios otorgados",
    "IGV - Retiro de bienes",
    "Tarjetas Visanet",
    "Tarjetas Mercadopago",
    "Tarjetas MCM",
    "Tarjetas Expressnet",
    "Pago Izipay",
    "Tarjetas Diners",
    "Tarjetas Estilos",
    "Efectivo Activa",
    "Deposito BCP",
    "Deposito Scotiabank",
    "Deposito Interbank",
    "Deposito BBVA",
    "Tarjetas Openpay",
]
